#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Install AI skills for @anionzo/skill on Windows (PowerShell)
.DESCRIPTION
    Port of install-opencode-skills for Windows.
    Supports both interactive (npx) and silent (postinstall) modes.
#>

param(
    [string]$ProjectDir = $null,
    [switch]$Help,
    [switch]$Yes,
    [string]$Platform = ""
)

if ($Help) {
    Write-Host "Usage:"
    Write-Host "  npx @anionzo/skill"
    Write-Host "  npx @anionzo/skill --yes"
    Write-Host "  npx @anionzo/skill --platform opencode,claude,copilot"
    Write-Host "  npm install @anionzo/skill"
    Write-Host "  pwsh scripts/install-opencode-skills.ps1 [-Yes] [-Platform value] [project-dir]"
    Write-Host ""
    Write-Host "Notes:"
    Write-Host "  - Interactive mode shows a simple menu (Windows friendly)"
    Write-Host "  - Silent postinstall installs default platforms"
    Write-Host "  - -Yes skips the picker and installs all top-level agent files"
    Write-Host "  - -Platform accepts: opencode, claude, agents, gemini, copilot, gitignore"
    exit 0
}

# Determine project root
if ($ProjectDir) {
    $PROJECT = $ProjectDir
} elseif ($env:npm_lifecycle_event -eq "postinstall" -and $env:npm_config_local_prefix) {
    $PROJECT = $env:npm_config_local_prefix
} elseif ($env:INIT_CWD) {
    $PROJECT = $env:INIT_CWD
} else {
    $PROJECT = Get-Location
}

$PROJECT = (Resolve-Path $PROJECT).Path

# Don't install into ourselves
if ($PROJECT -like "*node_modules*") {
    exit 0
}

$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$ROOT = Split-Path -Parent $SCRIPT_DIR

function Install-Skills {
    param(
        [string]$TargetDir,
        [string]$FormatName
    )

    New-Item -ItemType Directory -Force -Path $TargetDir | Out-Null
    $count = 0

    Get-ChildItem "$ROOT/skills" -Directory | ForEach-Object {
        $skillDir = $_.FullName
        $skillName = $_.Name
        $skillMd = Join-Path $skillDir "SKILL.md"
        $metaYaml = Join-Path $skillDir "meta.yaml"

        if (-not (Test-Path $skillMd) -or -not (Test-Path $metaYaml)) { return }

        $summary = (Get-Content $metaYaml | Select-String '^summary:\s*(.+)' | ForEach-Object { $_.Matches.Groups[1].Value })[0]

        $targetSkillDir = Join-Path $TargetDir $skillName
        Remove-Item -Recurse -Force -Path $targetSkillDir -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Force -Path $targetSkillDir | Out-Null

        Copy-Item $metaYaml (Join-Path $targetSkillDir "meta.yaml")

        $content = @"
---
name: $skillName
description: "$summary"
license: MIT
---
"@
        $content + (Get-Content $skillMd -Raw) | Out-File -FilePath (Join-Path $targetSkillDir "SKILL.md") -Encoding utf8

        $examplesMd = Join-Path $skillDir "examples.md"
        if (Test-Path $examplesMd) {
            Copy-Item $examplesMd (Join-Path $targetSkillDir "examples.md")
        }

        $refsDir = Join-Path $skillDir "references"
        if (Test-Path $refsDir) {
            Copy-Item -Recurse $refsDir (Join-Path $targetSkillDir "references") -ErrorAction SilentlyContinue
        }

        $count++
    }

    Write-Host "  $FormatName`: $count skills -> $TargetDir"
}

function Copy-Tree {
    param(
        [string]$SrcDir,
        [string]$TargetDir
    )

    Remove-Item -Recurse -Force -Path $TargetDir -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force -Path (Split-Path $TargetDir) | Out-Null
    Copy-Item -Recurse $SrcDir $TargetDir
}

function Install-SharedLibrary {
    $sharedRoot = Join-Path $PROJECT ".anionzo"

    Install-Skills (Join-Path $sharedRoot "skills") "Shared Library"
    Copy-Tree (Join-Path $ROOT "knowledge") (Join-Path $sharedRoot "knowledge")
    Copy-Tree (Join-Path $ROOT "docs") (Join-Path $sharedRoot "docs")

    Write-Host "  Shared docs/knowledge -> $sharedRoot"
}

function Build-Catalog {
    $catalog = ""
    Get-ChildItem "$ROOT/skills/*/meta.yaml" | ForEach-Object {
        $meta = Get-Content $_.FullName -Raw
        $name = ($meta | Select-String 'name:\s*(\S+)' | ForEach-Object { $_.Matches.Groups[1].Value })
        $summary = ($meta | Select-String 'summary:\s*(.+)' | ForEach-Object { $_.Matches.Groups[1].Value })
        if ($name) {
            $catalog += "$name|$summary`n"
        }
    }
    return $catalog
}

function Write-AgentFile {
    param(
        [string]$Title,
        [string]$Target,
        [string]$Catalog
    )

    $content = @"
<!-- Generated by @anionzo/skill -->
# $Title

Start with `.anionzo/skills/using-skills/SKILL.md` when the task shape is unclear. Use one primary skill at a time, then pull in the smallest amount of supporting knowledge needed.

## Core Files

- `.anionzo/skills/using-skills/SKILL.md`
- `.anionzo/knowledge/global/engineering-principles.md`
- `.anionzo/knowledge/global/review-heuristics.md`
- `.anionzo/knowledge/global/debugging-patterns.md`
- `.anionzo/knowledge/global/evidence-before-claims.md`
- `.anionzo/knowledge/global/skill-triggering-rules.md`
- `.anionzo/docs/skill-spec.md`

## Working Rules

- Prefer the smallest correct change.
- Read the repo and nearby patterns before editing.
- Ask only the shortest blocking question when a decision is missing.
- Verify important claims with code, tests, or commands when possible.
- Keep summaries concise and grounded in files you inspected.

## Skill Catalog

"@
    $Catalog.Split("`n") | ForEach-Object {
        if ($_.Trim()) {
            $parts = $_.Split('|')
            if ($parts.Count -ge 2) {
                $content += "- ``$($parts[0])``: $($parts[1])`n"
            }
        }
    }

    $content += @"

## Suggested Flow

1. Route with `using-skills` when unsure.
2. Load one primary skill that matches the current task.
3. Pull in `.anionzo/knowledge/project/` notes when working inside a real project.
4. Verify the outcome before declaring the work complete.
"@

    $content | Out-File -FilePath $Target -Encoding utf8
}

function Update-Gitignore {
    param($Selected)

    $gitignore = Join-Path $PROJECT ".gitignore"
    $entries = @(".anionzo/")

    if ($Selected.OpenCode) { $entries += @(".opencode/", "OPENCODE.md") }
    if ($Selected.Claude) { $entries += @(".claude/", "CLAUDE.md") }
    if ($Selected.Agents) { $entries += @(".agents/", "AGENTS.md") }
    if ($Selected.Gemini) { $entries += "GEMINI.md" }
    if ($Selected.Copilot) { $entries += ".github/copilot-instructions.md" }

    if ($entries.Count -eq 1) {
        Write-Host "  .gitignore: skipped (no platform files selected)"
        return
    }

    New-Item -ItemType File -Force -Path $gitignore | Out-Null

    $content = Get-Content $gitignore -ErrorAction SilentlyContinue
    $headerNeeded = -not ($content -like "*@anionzo/skill*")

    $missing = @()
    foreach ($entry in $entries) {
        if (-not ($content -like "*$entry*")) {
            $missing += $entry
        }
    }

    if ($missing.Count -eq 0) {
        Write-Host "  .gitignore: already up to date"
        return
    }

    if ($headerNeeded) {
        "`n# @anionzo/skill" | Add-Content $gitignore -Encoding utf8
    }

    foreach ($entry in $missing) {
        $entry | Add-Content $gitignore -Encoding utf8
    }

    Write-Host "  .gitignore: added $($missing.Count) entries -> $gitignore"
}

function New-SelectionState {
    return @{
        OpenCode = $false
        Claude = $false
        Agents = $false
        Gemini = $false
        Copilot = $false
        Gitignore = $false
    }
}

function Enable-Platform {
    param(
        [hashtable]$Selected,
        [string]$Name
    )

    switch ($Name.ToLowerInvariant()) {
        "opencode" { $Selected.OpenCode = $true }
        "claude" { $Selected.Claude = $true }
        "agents" { $Selected.Agents = $true }
        "generic" { $Selected.Agents = $true }
        "gemini" { $Selected.Gemini = $true }
        "copilot" { $Selected.Copilot = $true }
        "github-copilot" { $Selected.Copilot = $true }
        "gitignore" { $Selected.Gitignore = $true }
        "all" {
            $Selected.OpenCode = $true
            $Selected.Claude = $true
            $Selected.Agents = $true
            $Selected.Gemini = $true
            $Selected.Copilot = $true
        }
        default { throw "Unknown platform: $Name" }
    }
}

function Get-SelectionFromPlatformArg {
    param([string]$Raw)

    $selected = New-SelectionState
    foreach ($item in ($Raw -split ',')) {
        $name = $item.Trim()
        if (-not [string]::IsNullOrWhiteSpace($name)) {
            Enable-Platform $selected $name
        }
    }
    return $selected
}

function Invoke-SelectedInstall {
    param([hashtable]$Selected)

    $total = @($Selected.OpenCode, $Selected.Claude, $Selected.Agents, $Selected.Gemini, $Selected.Copilot | Where-Object { $_ }).Count
    if ($total -eq 0) {
        Write-Host "`n  Nothing selected. Exiting.`n" -ForegroundColor Red
        exit 0
    }

    Write-Host "`n  Installing...`n" -ForegroundColor Green

    Install-SharedLibrary
    $catalog = Build-Catalog

    if ($Selected.OpenCode) {
        Install-Skills (Join-Path $PROJECT ".opencode/skills") "OpenCode"
        Write-AgentFile "OpenCode Instructions" (Join-Path $PROJECT "OPENCODE.md") $catalog
        Write-Host "  -> OPENCODE.md"
    }
    if ($Selected.Claude) {
        Install-Skills (Join-Path $PROJECT ".claude/skills") "Claude"
        Write-AgentFile "Claude Code Instructions" (Join-Path $PROJECT "CLAUDE.md") $catalog
        Write-Host "  -> CLAUDE.md"
    }
    if ($Selected.Agents) {
        Install-Skills (Join-Path $PROJECT ".agents/skills") "Agents"
        Write-AgentFile "Generic Agent Instructions" (Join-Path $PROJECT "AGENTS.md") $catalog
        Write-Host "  -> AGENTS.md"
    }
    if ($Selected.Gemini) {
        Write-AgentFile "Gemini Instructions" (Join-Path $PROJECT "GEMINI.md") $catalog
        Write-Host "  -> GEMINI.md"
    }
    if ($Selected.Copilot) {
        New-Item -ItemType Directory -Force -Path (Join-Path $PROJECT ".github") | Out-Null
        Write-AgentFile "GitHub Copilot Instructions" (Join-Path $PROJECT ".github/copilot-instructions.md") $catalog
        Write-Host "  -> .github/copilot-instructions.md"
    }
    if ($Selected.Gitignore) {
        Update-Gitignore $Selected
    }
}

# Interactive detection
$isInteractive = ($env:npm_lifecycle_event -ne "postinstall") -and ($Host.Name -eq "ConsoleHost")

if (-not [string]::IsNullOrWhiteSpace($Platform)) {
    $selected = Get-SelectionFromPlatformArg $Platform
    Invoke-SelectedInstall $selected
} elseif ($Yes) {
    $selected = New-SelectionState
    Enable-Platform $selected "all"
    Invoke-SelectedInstall $selected
} elseif ($isInteractive) {
    Write-Host "`n  @anionzo/skill -- AI Skill Library" -ForegroundColor Cyan
    Write-Host "  ==================================`n" -ForegroundColor Cyan
    Write-Host "Chọn các platform bạn muốn cài (nhập số, cách nhau bởi dấu phẩy, ví dụ: 1,2,5):`n" -ForegroundColor Yellow

    $platforms = @(
        "1. OpenCode        (.opencode/skills/ + OPENCODE.md)",
        "2. Claude Code     (.claude/skills/   + CLAUDE.md)",
        "3. Agents (generic)(.agents/skills/   + AGENTS.md)",
        "4. Gemini CLI      (GEMINI.md)",
        "5. GitHub Copilot  (.github/copilot-instructions.md)",
        "6. Update .gitignore"
    )

    for ($i = 0; $i -lt $platforms.Count; $i++) {
        Write-Host $platforms[$i]
    }

    $selection = Read-Host "`nNhập lựa chọn (Enter = tất cả)"
    $selectedIndices = if ($selection.Trim() -eq "") { 0..5 } else { $selection -split ',' | ForEach-Object { $_.Trim() - 1 } }

    $selected = @{
        OpenCode = $selectedIndices -contains 0
        Claude   = $selectedIndices -contains 1
        Agents   = $selectedIndices -contains 2
        Gemini   = $selectedIndices -contains 3
        Copilot  = $selectedIndices -contains 4
        Gitignore = $selectedIndices -contains 5
    }

    Invoke-SelectedInstall $selected
} else {
    # Silent mode (postinstall)
    Write-Host "`n  @anionzo/skill — AI Skill Library" -ForegroundColor Cyan
    Write-Host "  ==================================`n" -ForegroundColor Cyan
    Write-Host "  Installing skills (postinstall)...`n" -ForegroundColor Green

    Install-SharedLibrary

    Install-Skills (Join-Path $PROJECT ".opencode/skills") "OpenCode"
    Install-Skills (Join-Path $PROJECT ".claude/skills") "Claude"
    Install-Skills (Join-Path $PROJECT ".agents/skills") "Agents"
}

Write-Host "`n  Done! Use /skill in your agent to see available skills.`n" -ForegroundColor Green
